#!/bin/bash
# Script para actualizar la API Key de Gemini de forma segura

echo "🔐 ACTUALIZACIÓN SEGURA DE API KEY DE GEMINI"
echo "=========================================="
echo ""
echo "⚠️  IMPORTANTE: Tu API key actual de Gemini fue reportada como filtrada (leaked)"
echo "    Google la ha bloqueado automáticamente por seguridad."
echo ""
echo "📋 PASOS A SEGUIR:"
echo ""
echo "1. Ve a: https://aistudio.google.com/apikey"
echo "2. Inicia sesión con tu cuenta de Google"
echo "3. ELIMINA la API key antigua (la que termina en ...1DU)"
echo "4. Haz clic en 'Create API key'"
echo "5. Copia la nueva API key"
echo ""
echo "6. Ejecuta este comando (reemplaza YOUR_NEW_KEY con tu nueva key):"
echo ""
echo "   sed -i '' 's/GEMINI_API_KEY=.*/GEMINI_API_KEY=YOUR_NEW_KEY/' .env"
echo ""
echo "7. Verifica que NO esté en el repositorio:"
echo ""
echo "   git status"
echo ""
echo "8. Si ves .env en la lista, agrégalo a .gitignore:"
echo ""
echo "   echo '.env' >> .gitignore"
echo "   git add .gitignore"
echo "   git commit -m 'Actualizar .gitignore para proteger .env'"
echo ""
echo "=========================================="
echo ""
echo "⚠️  NUNCA subas archivos .env a GitHub"
echo "⚠️  NUNCA compartas tu API key públicamente"
echo ""
read -p "Presiona ENTER cuando hayas completado los pasos anteriores..."
echo ""
echo "✅ Reiniciando servidor Django..."
