# Generated by Django 5.2.8 on 2025-11-09 19:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="ConfiguracionAPI",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "nombre_api",
                    models.CharField(
                        max_length=50, unique=True, verbose_name="Nombre API"
                    ),
                ),
                ("url_base", models.URLField(verbose_name="URL Base")),
                (
                    "token_activo",
                    models.BooleanField(default=True, verbose_name="Token Activo"),
                ),
                (
                    "fecha_ultima_consulta",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Última Consulta"
                    ),
                ),
                (
                    "consultas_realizadas",
                    models.PositiveIntegerField(
                        default=0, verbose_name="Consultas Realizadas"
                    ),
                ),
                (
                    "limite_consultas_diarias",
                    models.PositiveIntegerField(
                        blank=True, null=True, verbose_name="Límite Diario"
                    ),
                ),
            ],
            options={
                "verbose_name": "Configuración API",
                "verbose_name_plural": "Configuraciones API",
            },
        ),
        migrations.CreateModel(
            name="Parcela",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "nombre",
                    models.CharField(
                        max_length=200, verbose_name="Nombre de la Parcela"
                    ),
                ),
                (
                    "propietario",
                    models.CharField(max_length=200, verbose_name="Propietario"),
                ),
                (
                    "poligono_geojson",
                    models.TextField(
                        help_text="Polígono en formato GeoJSON con las coordenadas de la parcela",
                        verbose_name="Coordenadas GeoJSON",
                    ),
                ),
                (
                    "area_hectareas",
                    models.FloatField(
                        blank=True,
                        help_text="Área calculada automáticamente en hectáreas",
                        null=True,
                        verbose_name="Área (hectáreas)",
                    ),
                ),
                (
                    "fecha_registro",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Fecha de Registro"
                    ),
                ),
                (
                    "fecha_inicio_monitoreo",
                    models.DateField(verbose_name="Inicio Monitoreo"),
                ),
                (
                    "fecha_fin_monitoreo",
                    models.DateField(
                        blank=True, null=True, verbose_name="Fin Monitoreo"
                    ),
                ),
                ("activa", models.BooleanField(default=True, verbose_name="Activa")),
                (
                    "tipo_cultivo",
                    models.CharField(
                        blank=True, max_length=100, verbose_name="Tipo de Cultivo"
                    ),
                ),
                ("notas", models.TextField(blank=True, verbose_name="Notas")),
            ],
            options={
                "verbose_name": "Parcela",
                "verbose_name_plural": "Parcelas",
                "ordering": ["-fecha_registro"],
            },
        ),
        migrations.CreateModel(
            name="Informe",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "fecha_generacion",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Fecha Generación"
                    ),
                ),
                (
                    "periodo_analisis_meses",
                    models.PositiveIntegerField(
                        help_text="Número de meses analizados (6, 12, 24)",
                        verbose_name="Período Análisis (meses)",
                    ),
                ),
                (
                    "fecha_inicio_analisis",
                    models.DateField(verbose_name="Inicio Período"),
                ),
                ("fecha_fin_analisis", models.DateField(verbose_name="Fin Período")),
                (
                    "titulo",
                    models.CharField(max_length=300, verbose_name="Título del Informe"),
                ),
                (
                    "resumen_ejecutivo",
                    models.TextField(
                        help_text="Resumen generado automáticamente por IA",
                        verbose_name="Resumen Ejecutivo",
                    ),
                ),
                (
                    "analisis_tendencias",
                    models.TextField(
                        blank=True,
                        help_text="Análisis detallado de tendencias NDVI, NDMI, SAVI",
                        verbose_name="Análisis de Tendencias",
                    ),
                ),
                (
                    "conclusiones_ia",
                    models.TextField(
                        blank=True,
                        help_text="Conclusiones generadas por análisis IA local",
                        verbose_name="Conclusiones IA",
                    ),
                ),
                (
                    "recomendaciones",
                    models.TextField(
                        blank=True,
                        help_text="Recomendaciones técnicas basadas en los datos",
                        verbose_name="Recomendaciones",
                    ),
                ),
                (
                    "archivo_pdf",
                    models.FileField(
                        blank=True,
                        null=True,
                        upload_to="informes/pdfs/%Y/%m/",
                        verbose_name="Archivo PDF",
                    ),
                ),
                (
                    "mapa_ndvi_imagen",
                    models.ImageField(
                        blank=True,
                        null=True,
                        upload_to="informes/mapas/%Y/%m/",
                        verbose_name="Mapa NDVI",
                    ),
                ),
                (
                    "grafico_tendencias",
                    models.ImageField(
                        blank=True,
                        null=True,
                        upload_to="informes/graficos/%Y/%m/",
                        verbose_name="Gráfico Tendencias",
                    ),
                ),
                (
                    "ndvi_promedio_periodo",
                    models.FloatField(
                        blank=True, null=True, verbose_name="NDVI Promedio del Período"
                    ),
                ),
                (
                    "ndmi_promedio_periodo",
                    models.FloatField(
                        blank=True, null=True, verbose_name="NDMI Promedio del Período"
                    ),
                ),
                (
                    "savi_promedio_periodo",
                    models.FloatField(
                        blank=True, null=True, verbose_name="SAVI Promedio del Período"
                    ),
                ),
                (
                    "version_algoritmo",
                    models.CharField(
                        default="1.0", max_length=20, verbose_name="Versión Algoritmo"
                    ),
                ),
                (
                    "tiempo_procesamiento",
                    models.DurationField(
                        blank=True, null=True, verbose_name="Tiempo Procesamiento"
                    ),
                ),
                (
                    "parcela",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="informes",
                        to="informes.parcela",
                    ),
                ),
            ],
            options={
                "verbose_name": "Informe",
                "verbose_name_plural": "Informes",
                "ordering": ["-fecha_generacion"],
            },
        ),
        migrations.CreateModel(
            name="IndiceMensual",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("año", models.PositiveIntegerField(verbose_name="Año")),
                ("mes", models.PositiveIntegerField(verbose_name="Mes")),
                (
                    "ndvi_promedio",
                    models.FloatField(
                        blank=True,
                        help_text="Índice de Vegetación de Diferencia Normalizada (0 a 1)",
                        null=True,
                        verbose_name="NDVI Promedio",
                    ),
                ),
                (
                    "ndvi_maximo",
                    models.FloatField(
                        blank=True, null=True, verbose_name="NDVI Máximo"
                    ),
                ),
                (
                    "ndvi_minimo",
                    models.FloatField(
                        blank=True, null=True, verbose_name="NDVI Mínimo"
                    ),
                ),
                (
                    "ndmi_promedio",
                    models.FloatField(
                        blank=True,
                        help_text="Índice de Humedad de Diferencia Normalizada (-1 a 1)",
                        null=True,
                        verbose_name="NDMI Promedio",
                    ),
                ),
                (
                    "ndmi_maximo",
                    models.FloatField(
                        blank=True, null=True, verbose_name="NDMI Máximo"
                    ),
                ),
                (
                    "ndmi_minimo",
                    models.FloatField(
                        blank=True, null=True, verbose_name="NDMI Mínimo"
                    ),
                ),
                (
                    "savi_promedio",
                    models.FloatField(
                        blank=True,
                        help_text="Índice de Vegetación Ajustado al Suelo",
                        null=True,
                        verbose_name="SAVI Promedio",
                    ),
                ),
                (
                    "savi_maximo",
                    models.FloatField(
                        blank=True, null=True, verbose_name="SAVI Máximo"
                    ),
                ),
                (
                    "savi_minimo",
                    models.FloatField(
                        blank=True, null=True, verbose_name="SAVI Mínimo"
                    ),
                ),
                (
                    "temperatura_promedio",
                    models.FloatField(
                        blank=True, null=True, verbose_name="Temperatura Promedio (°C)"
                    ),
                ),
                (
                    "temperatura_maxima",
                    models.FloatField(
                        blank=True, null=True, verbose_name="Temperatura Máxima"
                    ),
                ),
                (
                    "temperatura_minima",
                    models.FloatField(
                        blank=True, null=True, verbose_name="Temperatura Mínima"
                    ),
                ),
                (
                    "precipitacion_total",
                    models.FloatField(
                        blank=True, null=True, verbose_name="Precipitación Total (mm)"
                    ),
                ),
                (
                    "nubosidad_promedio",
                    models.FloatField(
                        blank=True,
                        help_text="Porcentaje promedio de nubosidad durante el mes",
                        null=True,
                        verbose_name="Nubosidad Promedio (%)",
                    ),
                ),
                (
                    "fecha_consulta_api",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Fecha Consulta API"
                    ),
                ),
                (
                    "fuente_datos",
                    models.CharField(
                        default="EOSDA", max_length=50, verbose_name="Fuente de Datos"
                    ),
                ),
                (
                    "calidad_datos",
                    models.CharField(
                        choices=[
                            ("excelente", "Excelente"),
                            ("buena", "Buena"),
                            ("regular", "Regular"),
                            ("pobre", "Pobre"),
                        ],
                        default="buena",
                        max_length=20,
                        verbose_name="Calidad de Datos",
                    ),
                ),
                (
                    "parcela",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="indices_mensuales",
                        to="informes.parcela",
                    ),
                ),
            ],
            options={
                "verbose_name": "Índice Mensual",
                "verbose_name_plural": "Índices Mensuales",
                "ordering": ["-año", "-mes"],
                "unique_together": {("parcela", "año", "mes")},
            },
        ),
    ]
