# Generated by Django 5.2.8 on 2025-11-09 20:46

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("informes", "0002_remove_parcela_poligono_geojson_parcela_centroide_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="ClienteInvitacion",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("token", models.CharField(max_length=32, unique=True)),
                ("nombre_cliente", models.CharField(max_length=200)),
                (
                    "email_cliente",
                    models.EmailField(blank=True, max_length=254, null=True),
                ),
                (
                    "telefono_cliente",
                    models.CharField(blank=True, max_length=20, null=True),
                ),
                (
                    "estado",
                    models.CharField(
                        choices=[
                            ("pendiente", "Pendiente"),
                            ("utilizada", "Utilizada"),
                            ("expirada", "Expirada"),
                            ("cancelada", "Cancelada"),
                        ],
                        default="pendiente",
                        max_length=20,
                    ),
                ),
                ("fecha_creacion", models.DateTimeField(auto_now_add=True)),
                ("fecha_expiracion", models.DateTimeField()),
                ("fecha_utilizacion", models.DateTimeField(blank=True, null=True)),
                (
                    "costo_servicio",
                    models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
                ),
                ("pagado", models.BooleanField(default=False)),
                ("fecha_pago", models.DateTimeField(blank=True, null=True)),
                ("notas_pago", models.TextField(blank=True, null=True)),
                (
                    "creado_por",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "parcela",
                    models.OneToOneField(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="invitacion_cliente",
                        to="informes.parcela",
                    ),
                ),
            ],
            options={
                "verbose_name": "Invitación de Cliente",
                "verbose_name_plural": "Invitaciones de Clientes",
                "ordering": ["-fecha_creacion"],
            },
        ),
        migrations.CreateModel(
            name="RegistroEconomico",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "tipo_servicio",
                    models.CharField(
                        choices=[
                            ("analisis_basico", "Análisis Básico"),
                            ("analisis_completo", "Análisis Completo"),
                            ("monitoreo_mensual", "Monitoreo Mensual"),
                            ("informe_personalizado", "Informe Personalizado"),
                            ("consultoria", "Consultoría"),
                        ],
                        default="analisis_basico",
                        max_length=30,
                    ),
                ),
                ("descripcion", models.TextField()),
                (
                    "valor_servicio",
                    models.DecimalField(decimal_places=2, max_digits=12),
                ),
                (
                    "descuento",
                    models.DecimalField(decimal_places=2, default=0.0, max_digits=5),
                ),
                ("valor_final", models.DecimalField(decimal_places=2, max_digits=12)),
                ("pagado", models.BooleanField(default=False)),
                ("fecha_pago", models.DateTimeField(blank=True, null=True)),
                (
                    "metodo_pago",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                (
                    "referencia_pago",
                    models.CharField(blank=True, max_length=200, null=True),
                ),
                ("fecha_servicio", models.DateTimeField(auto_now_add=True)),
                ("notas", models.TextField(blank=True, null=True)),
                (
                    "invitacion",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="registros_economicos",
                        to="informes.clienteinvitacion",
                    ),
                ),
                (
                    "parcela",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="registros_economicos",
                        to="informes.parcela",
                    ),
                ),
            ],
            options={
                "verbose_name": "Registro Económico",
                "verbose_name_plural": "Registros Económicos",
                "ordering": ["-fecha_servicio"],
            },
        ),
    ]
