# Generated by Django 5.2.8 on 2025-11-09 23:12

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("informes", "0005_parcela_eosda_errores_and_more"),
    ]

    operations = []
