# Generated by Django 5.2.8 on 2025-11-11 13:06

import datetime
import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("informes", "0006_auto_20251109_1812"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="CacheDatosEOSDA",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "field_id",
                    models.CharField(
                        db_index=True, max_length=100, verbose_name="Field ID de EOSDA"
                    ),
                ),
                (
                    "fecha_inicio",
                    models.DateField(db_index=True, verbose_name="Fecha Inicio"),
                ),
                (
                    "fecha_fin",
                    models.DateField(db_index=True, verbose_name="Fecha Fin"),
                ),
                (
                    "indices",
                    models.CharField(
                        help_text="Formato: ndvi,ndmi,savi",
                        max_length=100,
                        verbose_name="Índices Solicitados",
                    ),
                ),
                (
                    "cache_key",
                    models.CharField(
                        db_index=True,
                        help_text="Hash único generado: field_id + fechas + indices",
                        max_length=255,
                        unique=True,
                        verbose_name="Clave de Caché",
                    ),
                ),
                (
                    "datos_json",
                    models.JSONField(
                        help_text="Respuesta completa de EOSDA en formato JSON",
                        verbose_name="Datos en JSON",
                    ),
                ),
                (
                    "task_id",
                    models.CharField(
                        blank=True,
                        max_length=100,
                        null=True,
                        verbose_name="Task ID de EOSDA",
                    ),
                ),
                (
                    "num_escenas",
                    models.IntegerField(
                        default=0,
                        help_text="Cantidad de escenas satelitales retornadas",
                        verbose_name="Número de Escenas",
                    ),
                ),
                (
                    "calidad_promedio",
                    models.FloatField(
                        blank=True,
                        help_text="Nubosidad promedio de las escenas (%)",
                        null=True,
                        verbose_name="Calidad Promedio",
                    ),
                ),
                ("creado_en", models.DateTimeField(auto_now_add=True)),
                (
                    "usado_en",
                    models.DateTimeField(
                        auto_now=True,
                        help_text="Actualizado cada vez que se reutiliza el caché",
                        verbose_name="Último Uso",
                    ),
                ),
                (
                    "veces_usado",
                    models.IntegerField(
                        default=0,
                        help_text="Contador de cuántas veces se ha reutilizado este caché",
                        verbose_name="Veces Reutilizado",
                    ),
                ),
                (
                    "valido_hasta",
                    models.DateTimeField(
                        help_text="Fecha de expiración del caché (7 días típicamente)",
                        verbose_name="Válido Hasta",
                    ),
                ),
            ],
            options={
                "verbose_name": "Caché de Datos EOSDA",
                "verbose_name_plural": "Caché de Datos EOSDA",
                "ordering": ["-creado_en"],
                "indexes": [
                    models.Index(
                        fields=["field_id", "fecha_inicio", "fecha_fin"],
                        name="informes_ca_field_i_7a5936_idx",
                    ),
                    models.Index(
                        fields=["cache_key"], name="informes_ca_cache_k_0bd0ff_idx"
                    ),
                    models.Index(
                        fields=["valido_hasta"], name="informes_ca_valido__94ed5a_idx"
                    ),
                ],
            },
        ),
        migrations.CreateModel(
            name="ConfiguracionReporte",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "fecha_inicio",
                    models.DateField(
                        help_text="Inicio del período de análisis",
                        verbose_name="Fecha de Inicio",
                    ),
                ),
                (
                    "fecha_fin",
                    models.DateField(
                        default=datetime.date.today,
                        help_text="Fin del período de análisis",
                        verbose_name="Fecha de Fin",
                    ),
                ),
                (
                    "plan",
                    models.CharField(
                        choices=[
                            ("basico_6m", "6 Meses - Básico"),
                            ("estandar_1y", "1 Año - Estándar"),
                            ("avanzado_2y", "2 Años - Avanzado"),
                            ("personalizado", "Personalizado"),
                        ],
                        default="basico_6m",
                        max_length=20,
                        verbose_name="Plan",
                    ),
                ),
                (
                    "incluir_ndvi",
                    models.BooleanField(
                        default=True,
                        help_text="Índice de Vegetación (salud del cultivo)",
                        verbose_name="Incluir NDVI",
                    ),
                ),
                (
                    "incluir_ndmi",
                    models.BooleanField(
                        default=False,
                        help_text="Índice de Humedad (estrés hídrico)",
                        verbose_name="Incluir NDMI",
                    ),
                ),
                (
                    "incluir_savi",
                    models.BooleanField(
                        default=False,
                        help_text="Índice Ajustado de Suelo (cobertura)",
                        verbose_name="Incluir SAVI",
                    ),
                ),
                (
                    "incluir_imagenes",
                    models.BooleanField(
                        default=False,
                        help_text="Imágenes satelitales en el reporte PDF",
                        verbose_name="Incluir Imágenes",
                    ),
                ),
                (
                    "frecuencia_imagenes",
                    models.CharField(
                        choices=[
                            ("mensual", "Mensual (1 imagen/mes)"),
                            ("bimensual", "Bimensual (1 imagen cada 2 meses)"),
                            ("trimestral", "Trimestral (1 imagen cada 3 meses)"),
                        ],
                        default="mensual",
                        max_length=20,
                        verbose_name="Frecuencia de Imágenes",
                    ),
                ),
                (
                    "max_nubosidad",
                    models.IntegerField(
                        default=50,
                        help_text="Porcentaje máximo de nubes (30% ideal, 50% aceptable)",
                        validators=[
                            django.core.validators.MinValueValidator(0),
                            django.core.validators.MaxValueValidator(100),
                        ],
                        verbose_name="Máxima Nubosidad Permitida (%)",
                    ),
                ),
                (
                    "costo_estimado",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("0.00"),
                        help_text="Cálculo automático según configuración",
                        max_digits=10,
                        verbose_name="Costo Estimado (USD)",
                    ),
                ),
                ("creado_en", models.DateTimeField(auto_now_add=True)),
                ("actualizado_en", models.DateTimeField(auto_now=True)),
                (
                    "reporte_generado",
                    models.BooleanField(default=False, verbose_name="Reporte Generado"),
                ),
                (
                    "fecha_generacion",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Fecha de Generación"
                    ),
                ),
                (
                    "parcela",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="configuraciones_reporte",
                        to="informes.parcela",
                        verbose_name="Parcela",
                    ),
                ),
                (
                    "usuario",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="configuraciones_reporte",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Usuario",
                    ),
                ),
            ],
            options={
                "verbose_name": "Configuración de Reporte",
                "verbose_name_plural": "Configuraciones de Reportes",
                "ordering": ["-creado_en"],
                "indexes": [
                    models.Index(
                        fields=["parcela", "-creado_en"],
                        name="informes_co_parcela_aba29e_idx",
                    ),
                    models.Index(
                        fields=["usuario", "-creado_en"],
                        name="informes_co_usuario_9931c6_idx",
                    ),
                ],
            },
        ),
        migrations.CreateModel(
            name="EstadisticaUsoEOSDA",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "tipo_operacion",
                    models.CharField(
                        choices=[
                            ("field_management", "Field Management (Crear Campo)"),
                            ("statistics", "Statistics (Obtener Datos)"),
                            ("images", "Images (Imágenes Satelitales)"),
                            ("tiles", "Tiles (Mosaicos)"),
                        ],
                        max_length=50,
                        verbose_name="Tipo de Operación",
                    ),
                ),
                ("endpoint", models.CharField(max_length=200, verbose_name="Endpoint")),
                (
                    "metodo",
                    models.CharField(
                        default="POST", max_length=10, verbose_name="Método HTTP"
                    ),
                ),
                ("exitoso", models.BooleanField(default=True, verbose_name="Exitoso")),
                (
                    "codigo_respuesta",
                    models.IntegerField(
                        blank=True, null=True, verbose_name="Código HTTP"
                    ),
                ),
                (
                    "mensaje_error",
                    models.TextField(
                        blank=True, null=True, verbose_name="Mensaje de Error"
                    ),
                ),
                (
                    "tiempo_respuesta",
                    models.FloatField(
                        blank=True,
                        null=True,
                        verbose_name="Tiempo de Respuesta (segundos)",
                    ),
                ),
                (
                    "requests_consumidos",
                    models.IntegerField(
                        default=1,
                        help_text="Número de requests de API consumidos",
                        verbose_name="Requests Consumidos",
                    ),
                ),
                (
                    "desde_cache",
                    models.BooleanField(
                        default=False,
                        help_text="Si los datos se obtuvieron de caché (0 requests)",
                        verbose_name="Desde Caché",
                    ),
                ),
                (
                    "cache_key",
                    models.CharField(
                        blank=True,
                        max_length=255,
                        null=True,
                        verbose_name="Clave de Caché",
                    ),
                ),
                ("creado_en", models.DateTimeField(auto_now_add=True)),
                (
                    "parcela",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="estadisticas_eosda",
                        to="informes.parcela",
                        verbose_name="Parcela",
                    ),
                ),
                (
                    "usuario",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="estadisticas_eosda",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Usuario",
                    ),
                ),
            ],
            options={
                "verbose_name": "Estadística de Uso EOSDA",
                "verbose_name_plural": "Estadísticas de Uso EOSDA",
                "ordering": ["-creado_en"],
                "indexes": [
                    models.Index(
                        fields=["usuario", "-creado_en"],
                        name="informes_es_usuario_af1514_idx",
                    ),
                    models.Index(
                        fields=["parcela", "-creado_en"],
                        name="informes_es_parcela_e9c5d5_idx",
                    ),
                    models.Index(
                        fields=["tipo_operacion", "-creado_en"],
                        name="informes_es_tipo_op_f68540_idx",
                    ),
                ],
            },
        ),
    ]
