# Generated by Django 5.1.2 on 2025-11-19 16:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "informes",
            "0009_indicemensual_fecha_imagen_indicemensual_imagen_ndmi_and_more",
        ),
    ]

    operations = [
        migrations.AlterField(
            model_name="informe",
            name="archivo_pdf",
            field=models.FileField(
                blank=True,
                max_length=500,
                null=True,
                upload_to="informes/pdfs/%Y/%m/",
                verbose_name="Archivo PDF",
            ),
        ),
        migrations.AlterField(
            model_name="informe",
            name="grafico_tendencias",
            field=models.ImageField(
                blank=True,
                max_length=500,
                null=True,
                upload_to="informes/graficos/%Y/%m/",
                verbose_name="Gráfico Tendencias",
            ),
        ),
        migrations.AlterField(
            model_name="informe",
            name="mapa_ndvi_imagen",
            field=models.ImageField(
                blank=True,
                max_length=500,
                null=True,
                upload_to="informes/mapas/%Y/%m/",
                verbose_name="Mapa NDVI",
            ),
        ),
    ]
