# Generated by Django 5.1.2 on 2025-11-21 20:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("informes", "0010_alter_informe_archivo_pdf_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="indicemensual",
            name="analisis_gemini",
            field=models.JSONField(
                blank=True,
                help_text="Caché del análisis generado por Gemini AI para evitar regeneraciones costosas",
                null=True,
                verbose_name="Análisis Gemini AI (Caché)",
            ),
        ),
        migrations.AddField(
            model_name="indicemensual",
            name="fecha_analisis_gemini",
            field=models.DateTimeField(
                blank=True,
                help_text="Fecha y hora del último análisis de Gemini generado",
                null=True,
                verbose_name="Fecha Análisis Gemini",
            ),
        ),
    ]
