# Generated by Django 5.1.2 on 2025-11-25 12:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("informes", "0012_agregar_metadatos_espaciales"),
    ]

    operations = [
        migrations.AddField(
            model_name="clienteinvitacion",
            name="bloqueada",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="clienteinvitacion",
            name="intentos_uso",
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name="clienteinvitacion",
            name="ip_ultimo_intento",
            field=models.GenericIPAddressField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="clienteinvitacion",
            name="max_intentos",
            field=models.IntegerField(default=3),
        ),
    ]
