# Generated by Django 5.1.2 on 2025-11-25 13:45

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("informes", "0013_add_security_fields_to_invitacion"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="informe",
            name="configuracion",
            field=models.JSONField(
                blank=True,
                help_text="Configuración usada para generar este informe. Null = informe completo por defecto",
                null=True,
                verbose_name="Configuración Personalizada",
            ),
        ),
        migrations.CreateModel(
            name="PlantillaInforme",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "nombre",
                    models.CharField(
                        help_text="Ej: 'Informe de Riego', 'Análisis de Nitrógeno'",
                        max_length=100,
                        verbose_name="Nombre de la Plantilla",
                    ),
                ),
                (
                    "descripcion",
                    models.TextField(
                        blank=True,
                        help_text="Descripción de cuándo usar esta plantilla",
                        verbose_name="Descripción",
                    ),
                ),
                (
                    "configuracion",
                    models.JSONField(
                        help_text="Configuración completa de la plantilla",
                        verbose_name="Configuración",
                    ),
                ),
                (
                    "es_publica",
                    models.BooleanField(
                        default=False,
                        help_text="Si es pública, todos los usuarios pueden usarla",
                        verbose_name="Plantilla Pública",
                    ),
                ),
                (
                    "veces_usada",
                    models.PositiveIntegerField(default=0, verbose_name="Veces Usada"),
                ),
                (
                    "fecha_creacion",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Fecha de Creación"
                    ),
                ),
                (
                    "fecha_modificacion",
                    models.DateTimeField(
                        auto_now=True, verbose_name="Última Modificación"
                    ),
                ),
                (
                    "tipo_cultivo_sugerido",
                    models.CharField(
                        blank=True,
                        help_text="Para qué tipo de cultivo es ideal esta plantilla",
                        max_length=100,
                        verbose_name="Tipo de Cultivo Sugerido",
                    ),
                ),
                (
                    "usuario",
                    models.ForeignKey(
                        blank=True,
                        help_text="Usuario que creó la plantilla. Null = plantilla del sistema",
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="plantillas_informe",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Usuario",
                    ),
                ),
            ],
            options={
                "verbose_name": "Plantilla de Informe",
                "verbose_name_plural": "Plantillas de Informes",
                "ordering": ["-veces_usada", "-fecha_creacion"],
                "unique_together": {("nombre", "usuario")},
            },
        ),
    ]
