# Generated by Django 5.0.1 on 2025-12-30 16:08

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('informes', '0015_remove_clienteinvitacion_bloqueada_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AnalisisImagen',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_imagen', models.DateField()),
                ('indice', models.CharField(choices=[('ndvi', 'NDVI'), ('ndmi', 'NDMI'), ('savi', 'SAVI')], max_length=10)),
                ('url_imagen', models.URLField(max_length=500)),
                ('resultado_gemini', models.JSONField()),
                ('fecha_analisis', models.DateTimeField(auto_now_add=True)),
                ('hash_imagen', models.CharField(blank=True, db_index=True, max_length=64, null=True)),
                ('parcela', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='analisis_imagenes', to='informes.parcela')),
            ],
            options={
                'verbose_name': 'Análisis de Imagen Satelital (Gemini)',
                'verbose_name_plural': 'Análisis de Imágenes Satelitales (Gemini)',
                'unique_together': {('parcela', 'fecha_imagen', 'indice', 'url_imagen')},
            },
        ),
        migrations.CreateModel(
            name='InformeGenerado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_generacion', models.DateTimeField(auto_now_add=True)),
                ('tipo_analisis', models.CharField(choices=[('rapido', 'Análisis Rápido (10 imágenes)'), ('completo', 'Análisis Completo (30 imágenes)')], default='rapido', max_length=20)),
                ('num_imagenes_analizadas', models.IntegerField(default=0)),
                ('tokens_consumidos', models.IntegerField(default=0)),
                ('peticiones_api', models.IntegerField(default=0)),
                ('ruta_archivo', models.CharField(blank=True, max_length=500, null=True)),
                ('parcela', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='informes_generados', to='informes.parcela')),
                ('usuario', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Informe Generado',
                'verbose_name_plural': 'Informes Generados',
                'ordering': ['-fecha_generacion'],
                'indexes': [models.Index(fields=['fecha_generacion', 'usuario'], name='informes_in_fecha_g_287e2a_idx')],
            },
        ),
    ]
