# Generated by Django 5.2.8 on 2026-01-03 14:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('informes', '0016_analisisimagen_informegenerado'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='informegenerado',
            name='parcela',
        ),
        migrations.RemoveField(
            model_name='informegenerado',
            name='usuario',
        ),
        migrations.DeleteModel(
            name='AnalisisImagen',
        ),
        migrations.DeleteModel(
            name='InformeGenerado',
        ),
    ]
