# Generated by Django 5.2.8 on 2026-01-03 15:03

import django.core.validators
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('informes', '0018_add_informe_payment_system'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='informe',
            name='informes_in_estado__6a1b45_idx',
        ),
        migrations.RemoveIndex(
            model_name='informe',
            name='informes_in_fecha_v_4d2c81_idx',
        ),
        migrations.AlterField(
            model_name='informe',
            name='descuento_porcentaje',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=5, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)], verbose_name='Descuento %'),
        ),
        migrations.AlterField(
            model_name='informe',
            name='estado_pago',
            field=models.CharField(choices=[('pagado', '💰 Pagado'), ('pendiente', '⏳ Pendiente'), ('vencido', '⚠️ Vencido'), ('parcial', '📊 Pago Parcial'), ('cortesia', '🎁 Cortesía')], db_index=True, default='pendiente', max_length=20, verbose_name='Estado Pago'),
        ),
        migrations.AlterField(
            model_name='informe',
            name='fecha_pago',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Fecha Pago'),
        ),
        migrations.AlterField(
            model_name='informe',
            name='fecha_vencimiento',
            field=models.DateField(blank=True, db_index=True, null=True, verbose_name='Vencimiento'),
        ),
        migrations.AlterField(
            model_name='informe',
            name='metodo_pago',
            field=models.CharField(blank=True, max_length=100, verbose_name='Método Pago'),
        ),
        migrations.AlterField(
            model_name='informe',
            name='notas_pago',
            field=models.TextField(blank=True, verbose_name='Notas'),
        ),
        migrations.AlterField(
            model_name='informe',
            name='precio_base',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10, verbose_name='Precio Base'),
        ),
        migrations.AlterField(
            model_name='informe',
            name='precio_final',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10, verbose_name='Precio Final'),
        ),
        migrations.AlterField(
            model_name='informe',
            name='referencia_pago',
            field=models.CharField(blank=True, max_length=200, verbose_name='Referencia'),
        ),
    ]
