# Generated by Django 5.2.8 on 2026-01-03 15:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('informes', '0019_remove_informe_informes_in_estado__6a1b45_idx_and_more'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='informe',
            index=models.Index(fields=['estado_pago', 'fecha_generacion'], name='informes_in_estado__cad232_idx'),
        ),
        migrations.AddIndex(
            model_name='informe',
            index=models.Index(fields=['fecha_vencimiento'], name='informes_in_fecha_v_99785a_idx'),
        ),
    ]
