# Generated by Django 5.2.8 on 2026-01-03 15:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('informes', '0020_informe_informes_in_estado__cad232_idx_and_more'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='informe',
            name='informes_in_estado__cad232_idx',
        ),
        migrations.RemoveIndex(
            model_name='informe',
            name='informes_in_fecha_v_99785a_idx',
        ),
    ]
