# Generated by Django 5.1.2 on 2026-01-06 22:42

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('informes', '0021_remove_informe_informes_in_estado__cad232_idx_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='configuracionreporte',
            name='costo_estimado',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Cálculo automático según configuración en pesos colombianos', max_digits=10, verbose_name='Costo Estimado (COP)'),
        ),
    ]
