# Generated by Django 5.1.2 on 2026-01-10 15:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('informes', '0022_alter_configuracionreporte_costo_estimado'),
    ]

    operations = []
