# Generated by Django 5.1.2 on 2026-01-10 15:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('informes', '0023_parcela_ultima_calidad_datos_and_more'),
    ]

    operations = []
