# Generated by Django 5.0.1 on 2026-01-12 17:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('informes', '0026_parcela_ultima_calidad_datos_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='clienteinvitacion',
            name='moneda',
            field=models.CharField(choices=[('COP', 'Pesos Colombianos'), ('USD', 'Dólares USD')], default='COP', max_length=3),
        ),
    ]
