# Generated by Django 5.0.1 on 2026-01-23 13:59

import informes.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('informes', '0027_agregar_campo_moneda_invitacion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='indicemensual',
            name='imagen_ndmi',
            field=models.ImageField(blank=True, help_text='Imagen satelital del índice NDMI', null=True, upload_to=informes.models.upload_to_ndmi, verbose_name='Imagen NDMI'),
        ),
        migrations.AlterField(
            model_name='indicemensual',
            name='imagen_ndvi',
            field=models.ImageField(blank=True, help_text='Imagen satelital del índice NDVI', null=True, upload_to=informes.models.upload_to_ndvi, verbose_name='Imagen NDVI'),
        ),
        migrations.AlterField(
            model_name='indicemensual',
            name='imagen_savi',
            field=models.ImageField(blank=True, help_text='Imagen satelital del índice SAVI', null=True, upload_to=informes.models.upload_to_savi, verbose_name='Imagen SAVI'),
        ),
        migrations.CreateModel(
            name='UmbralesCultivo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_cultivo', models.CharField(help_text='Tipo de cultivo (Arroz, Maíz, Soya, etc.)', max_length=100)),
                ('fase_fenologica', models.CharField(default='general', help_text='Fase del cultivo (vegetativa, reproductiva, general)', max_length=50)),
                ('ndvi_critico_max', models.FloatField(default=0.3, help_text='NDVI máximo para detectar baja densidad vegetal crítica')),
                ('ndvi_moderado_max', models.FloatField(default=0.45, help_text='NDVI máximo para detectar baja densidad vegetal moderada')),
                ('ndvi_optimo_min', models.FloatField(default=0.7, help_text='NDVI mínimo para considerar cultivo en estado óptimo')),
                ('ndmi_estres_severo_max', models.FloatField(default=-0.08, help_text='NDMI máximo para detectar estrés hídrico severo')),
                ('ndmi_estres_moderado_max', models.FloatField(default=0.05, help_text='NDMI máximo para detectar déficit hídrico moderado')),
                ('ndmi_optimo_min', models.FloatField(default=0.2, help_text='NDMI mínimo para considerar humedad óptima')),
                ('savi_exposicion_severa_max', models.FloatField(default=0.25, help_text='SAVI máximo para detectar exposición de suelo severa')),
                ('savi_exposicion_moderada_max', models.FloatField(default=0.35, help_text='SAVI máximo para detectar exposición de suelo moderada')),
                ('savi_optimo_min', models.FloatField(default=0.5, help_text='SAVI mínimo para considerar cobertura óptima')),
                ('factor_penalizacion_crisis', models.FloatField(default=80.0, help_text='% de penalización por proporción de tiempo en crisis (0-100)')),
                ('penalizacion_maxima', models.FloatField(default=50.0, help_text='Penalización máxima permitida en % (límite de seguridad)')),
                ('area_minima_absoluta_ha', models.FloatField(default=0.05, help_text='Área mínima absoluta para detectar clusters (hectáreas)')),
                ('area_minima_porcentaje_lote', models.FloatField(default=0.5, help_text='Área mínima como % del lote (0.5 = 0.5%)')),
                ('fuente_bibliografia', models.TextField(blank=True, help_text='Referencias bibliográficas que validan estos umbrales')),
                ('validado_por', models.CharField(blank=True, help_text='Agrónomo o institución que validó estos valores', max_length=200)),
                ('fecha_validacion', models.DateField(auto_now_add=True, help_text='Fecha de validación de los umbrales')),
            ],
            options={
                'verbose_name': 'Umbrales de Cultivo',
                'verbose_name_plural': 'Umbrales de Cultivos',
                'ordering': ['tipo_cultivo', 'fase_fenologica'],
                'unique_together': {('tipo_cultivo', 'fase_fenologica')},
            },
        ),
    ]
