# Generated by Django - AgroTech Histórico
# Migración para agregar soporte de verificación legal opcional

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('informes', '0028_alter_indicemensual_imagen_ndmi_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='parcela',
            name='incluir_verificacion_legal',
            field=models.BooleanField(
                default=False,
                verbose_name='Incluir Verificación Legal',
                help_text='Verificar restricciones legales (retiros hídricos, áreas protegidas) en informes'
            ),
        ),
        migrations.AddField(
            model_name='parcela',
            name='verificacion_legal_fecha',
            field=models.DateTimeField(
                null=True,
                blank=True,
                verbose_name='Fecha Última Verificación Legal',
                help_text='Última vez que se verificaron restricciones legales'
            ),
        ),
        migrations.AddField(
            model_name='parcela',
            name='verificacion_legal_resultado',
            field=models.JSONField(
                null=True,
                blank=True,
                verbose_name='Resultado Verificación Legal',
                help_text='JSON con resultado completo de la última verificación legal'
            ),
        ),
        migrations.AddField(
            model_name='parcela',
            name='cumple_normativa',
            field=models.BooleanField(
                null=True,
                blank=True,
                verbose_name='Cumple Normativa Ambiental',
                help_text='Indica si cumple con todas las restricciones legales (última verificación)'
            ),
        ),
        migrations.AddField(
            model_name='parcela',
            name='area_cultivable_legal_ha',
            field=models.FloatField(
                null=True,
                blank=True,
                verbose_name='Área Cultivable Legal (ha)',
                help_text='Área cultivable después de descontar retiros legales'
            ),
        ),
    ]
