# Generated by Django 5.0.1 on 2026-04-01 19:42

import informes.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('informes', '0029_add_verificacion_legal'),
    ]

    operations = [
        migrations.AddField(
            model_name='configuracionreporte',
            name='incluir_evi',
            field=models.BooleanField(default=False, help_text='Vegetación Mejorada (estructura dosel, no se satura en alta biomasa)', verbose_name='Incluir EVI'),
        ),
        migrations.AddField(
            model_name='configuracionreporte',
            name='incluir_ndre',
            field=models.BooleanField(default=False, help_text='Índice de Borde Rojo (nitrógeno/clorofila en dosel denso)', verbose_name='Incluir NDRE'),
        ),
        migrations.AddField(
            model_name='indicemensual',
            name='evi_maximo',
            field=models.FloatField(blank=True, null=True, verbose_name='EVI Máximo'),
        ),
        migrations.AddField(
            model_name='indicemensual',
            name='evi_minimo',
            field=models.FloatField(blank=True, null=True, verbose_name='EVI Mínimo'),
        ),
        migrations.AddField(
            model_name='indicemensual',
            name='evi_promedio',
            field=models.FloatField(blank=True, help_text='Índice de Vegetación Mejorado - Estructura del dosel sin saturación (-1 a 1)', null=True, verbose_name='EVI Promedio'),
        ),
        migrations.AddField(
            model_name='indicemensual',
            name='imagen_evi',
            field=models.ImageField(blank=True, help_text='Imagen satelital del índice EVI', null=True, upload_to=informes.models.upload_to_evi, verbose_name='Imagen EVI'),
        ),
        migrations.AddField(
            model_name='indicemensual',
            name='imagen_ndre',
            field=models.ImageField(blank=True, help_text='Imagen satelital del índice NDRE', null=True, upload_to=informes.models.upload_to_ndre, verbose_name='Imagen NDRE'),
        ),
        migrations.AddField(
            model_name='indicemensual',
            name='ndre_maximo',
            field=models.FloatField(blank=True, null=True, verbose_name='NDRE Máximo'),
        ),
        migrations.AddField(
            model_name='indicemensual',
            name='ndre_minimo',
            field=models.FloatField(blank=True, null=True, verbose_name='NDRE Mínimo'),
        ),
        migrations.AddField(
            model_name='indicemensual',
            name='ndre_promedio',
            field=models.FloatField(blank=True, help_text='Índice de Borde Rojo - Clorofila/Nitrógeno en dosel denso (-1 a 1)', null=True, verbose_name='NDRE Promedio'),
        ),
    ]
