# Generated by Django 5.2.8 on 2026-03-14 15:11

import django.contrib.gis.db.models.fields
import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("informes", "0029_add_verificacion_legal"),
    ]

    operations = [
        migrations.CreateModel(
            name="DemoToken",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "token",
                    models.UUIDField(
                        db_index=True, default=uuid.uuid4, editable=False, unique=True
                    ),
                ),
                (
                    "nombre_completo",
                    models.CharField(blank=True, default="", max_length=200),
                ),
                ("telefono", models.CharField(blank=True, default="", max_length=20)),
                ("email", models.EmailField(blank=True, default="", max_length=254)),
                (
                    "departamento",
                    models.CharField(blank=True, default="", max_length=100),
                ),
                ("municipio", models.CharField(blank=True, default="", max_length=100)),
                (
                    "notas_comerciales",
                    models.TextField(
                        blank=True,
                        default="",
                        help_text="Notas internas - contexto de la conversación por WhatsApp",
                    ),
                ),
                (
                    "estado",
                    models.CharField(
                        choices=[
                            ("activo", "🟢 Activo"),
                            ("registrado", "📝 Registrado"),
                            ("usado", "✅ Usado"),
                            ("expirado", "⏰ Expirado"),
                        ],
                        default="activo",
                        max_length=15,
                    ),
                ),
                ("fecha_creacion", models.DateTimeField(auto_now_add=True)),
                ("fecha_expiracion", models.DateTimeField(blank=True, null=True)),
                ("fecha_registro", models.DateTimeField(blank=True, null=True)),
                ("fecha_uso", models.DateTimeField(blank=True, null=True)),
                ("ip_acceso", models.GenericIPAddressField(blank=True, null=True)),
                ("user_agent", models.TextField(blank=True, default="")),
            ],
            options={
                "verbose_name": "Token de Demo",
                "verbose_name_plural": "Tokens de Demo",
                "ordering": ["-fecha_creacion"],
            },
        ),
        migrations.CreateModel(
            name="DemoLead",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "geometria",
                    django.contrib.gis.db.models.fields.PolygonField(
                        blank=True, null=True, srid=4326
                    ),
                ),
                ("area_hectareas", models.FloatField(default=0)),
                ("centroide_lat", models.FloatField(default=0)),
                ("centroide_lon", models.FloatField(default=0)),
                ("ndvi_url", models.URLField(blank=True, default="", max_length=500)),
                ("ndmi_url", models.URLField(blank=True, default="", max_length=500)),
                ("savi_url", models.URLField(blank=True, default="", max_length=500)),
                (
                    "fecha_imagen_satelital",
                    models.DateField(
                        blank=True,
                        help_text="Fecha real de captura de la imagen Sentinel-2",
                        null=True,
                    ),
                ),
                (
                    "nubosidad_imagen",
                    models.FloatField(
                        blank=True,
                        help_text="Porcentaje de nubosidad de la imagen",
                        null=True,
                    ),
                ),
                ("fecha_demo", models.DateTimeField(auto_now_add=True)),
                (
                    "convertido_a_cliente",
                    models.BooleanField(
                        default=False,
                        help_text="¿El lead se convirtió en cliente pagante?",
                    ),
                ),
                (
                    "parcela_real_id",
                    models.IntegerField(
                        blank=True,
                        help_text="ID de la Parcela real si se convirtió en cliente",
                        null=True,
                    ),
                ),
                (
                    "token",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="lead",
                        to="informes.demotoken",
                    ),
                ),
            ],
            options={
                "verbose_name": "Lead de Demo",
                "verbose_name_plural": "Leads de Demo",
                "ordering": ["-fecha_demo"],
            },
        ),
    ]
