# Generated by Django 5.2.8 on 2026-03-14 16:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("informes", "0030_demo_token_y_lead"),
    ]

    operations = [
        migrations.AddField(
            model_name="demotoken",
            name="email_envio",
            field=models.CharField(
                blank=True,
                default="",
                help_text="Email al que se envió el link",
                max_length=200,
            ),
        ),
        migrations.AddField(
            model_name="demotoken",
            name="fecha_envio",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="demotoken",
            name="metodo_envio",
            field=models.CharField(
                choices=[
                    ("sin_enviar", "Sin enviar"),
                    ("whatsapp", "WhatsApp"),
                    ("email", "Email"),
                    ("link", "Solo Link"),
                ],
                default="sin_enviar",
                max_length=15,
            ),
        ),
        migrations.AddField(
            model_name="demotoken",
            name="nombre_prospecto",
            field=models.CharField(
                blank=True,
                default="",
                help_text="Nombre del prospecto (se llena al crear, antes de que se registre)",
                max_length=200,
            ),
        ),
        migrations.AddField(
            model_name="demotoken",
            name="telefono_envio",
            field=models.CharField(
                blank=True,
                default="",
                help_text="Teléfono al que se envió el link (WhatsApp)",
                max_length=20,
            ),
        ),
    ]
