# Generated by Django 5.2.8 on 2026-03-14 16:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("informes", "0031_demo_token_envio_fields"),
    ]

    operations = [
        migrations.CreateModel(
            name="DemoEosdaRequest",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "tipo_peticion",
                    models.CharField(
                        choices=[
                            ("stats", "Statistics API"),
                            ("imagery", "Imagery API"),
                            ("other", "Otro"),
                        ],
                        default="stats",
                        max_length=15,
                    ),
                ),
                ("endpoint", models.CharField(default="", max_length=200)),
                (
                    "resultado",
                    models.CharField(
                        choices=[
                            ("ok", "✅ Exitoso"),
                            ("error", "❌ Error"),
                            ("timeout", "⏰ Timeout"),
                            ("no_data", "⚠️ Sin datos"),
                        ],
                        default="ok",
                        max_length=15,
                    ),
                ),
                ("fecha", models.DateTimeField(auto_now_add=True)),
                (
                    "tiempo_respuesta_ms",
                    models.IntegerField(
                        default=0, help_text="Tiempo de respuesta en ms"
                    ),
                ),
                ("status_code", models.IntegerField(default=0)),
                (
                    "num_escenas",
                    models.IntegerField(
                        default=0, help_text="Escenas devueltas por EOSDA"
                    ),
                ),
                (
                    "indices_solicitados",
                    models.CharField(
                        default="NDVI,NDMI,SAVI",
                        help_text="Índices solicitados separados por coma",
                        max_length=50,
                    ),
                ),
                ("error_detalle", models.TextField(blank=True, default="")),
                (
                    "lead",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="eosda_requests",
                        to="informes.demolead",
                    ),
                ),
                (
                    "token",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="eosda_requests",
                        to="informes.demotoken",
                    ),
                ),
            ],
            options={
                "verbose_name": "Request EOSDA Demo",
                "verbose_name_plural": "Requests EOSDA Demo",
                "ordering": ["-fecha"],
            },
        ),
    ]
