# Generated by Django 5.1.2 on 2026-03-14 20:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("informes", "0032_add_demo_eosda_request_tracker"),
    ]

    operations = [
        migrations.AlterField(
            model_name="demolead",
            name="ndmi_url",
            field=models.CharField(blank=True, default="", max_length=500),
        ),
        migrations.AlterField(
            model_name="demolead",
            name="ndvi_url",
            field=models.CharField(blank=True, default="", max_length=500),
        ),
        migrations.AlterField(
            model_name="demolead",
            name="savi_url",
            field=models.CharField(blank=True, default="", max_length=500),
        ),
    ]
