# Generated by Django 5.2.8 on 2025-11-09 20:03

import django.contrib.gis.db.models.fields
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("informes", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="parcela",
            name="poligono_geojson",
        ),
        migrations.AddField(
            model_name="parcela",
            name="centroide",
            field=django.contrib.gis.db.models.fields.PointField(
                blank=True,
                help_text="Centro geométrico calculado automáticamente",
                null=True,
                srid=4326,
                verbose_name="Punto Central",
            ),
        ),
        migrations.AddField(
            model_name="parcela",
            name="coordenadas",
            field=models.TextField(
                blank=True,
                help_text="Representación GeoJSON para compatibilidad",
                verbose_name="GeoJSON (respaldo)",
            ),
        ),
        migrations.AddField(
            model_name="parcela",
            name="geometria",
            field=django.contrib.gis.db.models.fields.PolygonField(
                blank=True,
                help_text="Polígono definiendo los límites de la parcela",
                null=True,
                srid=4326,
                verbose_name="Geometría de la Parcela",
            ),
        ),
        migrations.AddField(
            model_name="parcela",
            name="perimetro_metros",
            field=models.FloatField(
                blank=True,
                help_text="Perímetro calculado automáticamente",
                null=True,
                verbose_name="Perímetro (metros)",
            ),
        ),
        migrations.AlterField(
            model_name="parcela",
            name="area_hectareas",
            field=models.FloatField(
                blank=True,
                help_text="Área calculada automáticamente usando PostGIS",
                null=True,
                verbose_name="Área (hectáreas)",
            ),
        ),
    ]
