# Generated by Django 5.2.8 on 2025-11-09 21:36

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("informes", "0003_clienteinvitacion_registroeconomico"),
    ]

    operations = [
        migrations.AddField(
            model_name="clienteinvitacion",
            name="descripcion_servicio",
            field=models.TextField(blank=True, default="Análisis satelital agrícola"),
        ),
    ]
