# Generated by Django 5.2.8 on 2025-11-09 23:11

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("informes", "0004_clienteinvitacion_descripcion_servicio"),
    ]

    operations = [
        migrations.AddField(
            model_name="parcela",
            name="eosda_errores",
            field=models.TextField(
                blank=True,
                help_text="Último error durante sincronización con EOSDA",
                null=True,
                verbose_name="Errores EOSDA",
            ),
        ),
        migrations.AddField(
            model_name="parcela",
            name="eosda_fecha_sincronizacion",
            field=models.DateTimeField(
                blank=True,
                help_text="Cuándo se sincronizó por última vez con EOSDA",
                null=True,
                verbose_name="Fecha Sincronización EOSDA",
            ),
        ),
        migrations.AddField(
            model_name="parcela",
            name="eosda_field_id",
            field=models.CharField(
                blank=True,
                help_text="ID único del campo en EOSDA después de sincronización",
                max_length=100,
                null=True,
                unique=True,
                verbose_name="EOSDA Field ID",
            ),
        ),
        migrations.AddField(
            model_name="parcela",
            name="eosda_nombre_campo",
            field=models.CharField(
                blank=True,
                help_text="Nombre del campo tal como aparece en EOSDA",
                max_length=200,
                null=True,
                verbose_name="Nombre en EOSDA",
            ),
        ),
        migrations.AddField(
            model_name="parcela",
            name="eosda_sincronizada",
            field=models.BooleanField(
                default=False,
                help_text="Indica si la parcela fue creada exitosamente en EOSDA",
                verbose_name="Sincronizada con EOSDA",
            ),
        ),
    ]
