# Generated by Django 5.2.8 on 2025-11-11 13:14

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("informes", "0007_cachedatoseosda_configuracionreporte_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name="cachedatoseosda",
            name="informes_ca_field_i_7a5936_idx",
        ),
        migrations.RemoveIndex(
            model_name="cachedatoseosda",
            name="informes_ca_cache_k_0bd0ff_idx",
        ),
        migrations.RemoveIndex(
            model_name="cachedatoseosda",
            name="informes_ca_valido__94ed5a_idx",
        ),
        migrations.RemoveIndex(
            model_name="configuracionreporte",
            name="informes_co_parcela_aba29e_idx",
        ),
        migrations.RemoveIndex(
            model_name="configuracionreporte",
            name="informes_co_usuario_9931c6_idx",
        ),
        migrations.RemoveIndex(
            model_name="estadisticausoeosda",
            name="informes_es_usuario_af1514_idx",
        ),
        migrations.RemoveIndex(
            model_name="estadisticausoeosda",
            name="informes_es_parcela_e9c5d5_idx",
        ),
        migrations.RemoveIndex(
            model_name="estadisticausoeosda",
            name="informes_es_tipo_op_f68540_idx",
        ),
        migrations.AlterField(
            model_name="cachedatoseosda",
            name="cache_key",
            field=models.CharField(db_index=True, max_length=255, unique=True),
        ),
        migrations.AlterField(
            model_name="cachedatoseosda",
            name="calidad_promedio",
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="cachedatoseosda",
            name="datos_json",
            field=models.JSONField(),
        ),
        migrations.AlterField(
            model_name="cachedatoseosda",
            name="fecha_fin",
            field=models.DateField(db_index=True),
        ),
        migrations.AlterField(
            model_name="cachedatoseosda",
            name="fecha_inicio",
            field=models.DateField(db_index=True),
        ),
        migrations.AlterField(
            model_name="cachedatoseosda",
            name="field_id",
            field=models.CharField(db_index=True, max_length=100),
        ),
        migrations.AlterField(
            model_name="cachedatoseosda",
            name="indices",
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name="cachedatoseosda",
            name="num_escenas",
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name="cachedatoseosda",
            name="task_id",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name="cachedatoseosda",
            name="usado_en",
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name="cachedatoseosda",
            name="valido_hasta",
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name="cachedatoseosda",
            name="veces_usado",
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name="configuracionreporte",
            name="costo_estimado",
            field=models.DecimalField(
                decimal_places=2, default=Decimal("0.00"), max_digits=10
            ),
        ),
        migrations.AlterField(
            model_name="configuracionreporte",
            name="fecha_fin",
            field=models.DateField(
                default=django.utils.timezone.now, verbose_name="Fecha de Fin"
            ),
        ),
        migrations.AlterField(
            model_name="configuracionreporte",
            name="fecha_generacion",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="configuracionreporte",
            name="fecha_inicio",
            field=models.DateField(verbose_name="Fecha de Inicio"),
        ),
        migrations.AlterField(
            model_name="configuracionreporte",
            name="frecuencia_imagenes",
            field=models.CharField(
                choices=[
                    ("mensual", "Mensual"),
                    ("bimensual", "Bimensual"),
                    ("trimestral", "Trimestral"),
                ],
                default="mensual",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="configuracionreporte",
            name="incluir_imagenes",
            field=models.BooleanField(default=False, verbose_name="Incluir Imágenes"),
        ),
        migrations.AlterField(
            model_name="configuracionreporte",
            name="incluir_ndmi",
            field=models.BooleanField(default=False, verbose_name="Incluir NDMI"),
        ),
        migrations.AlterField(
            model_name="configuracionreporte",
            name="incluir_ndvi",
            field=models.BooleanField(default=True, verbose_name="Incluir NDVI"),
        ),
        migrations.AlterField(
            model_name="configuracionreporte",
            name="incluir_savi",
            field=models.BooleanField(default=False, verbose_name="Incluir SAVI"),
        ),
        migrations.AlterField(
            model_name="configuracionreporte",
            name="max_nubosidad",
            field=models.IntegerField(
                default=50,
                validators=[
                    django.core.validators.MinValueValidator(0),
                    django.core.validators.MaxValueValidator(100),
                ],
            ),
        ),
        migrations.AlterField(
            model_name="configuracionreporte",
            name="reporte_generado",
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name="estadisticausoeosda",
            name="cache_key",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name="estadisticausoeosda",
            name="codigo_respuesta",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="estadisticausoeosda",
            name="desde_cache",
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name="estadisticausoeosda",
            name="endpoint",
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name="estadisticausoeosda",
            name="exitoso",
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name="estadisticausoeosda",
            name="mensaje_error",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="estadisticausoeosda",
            name="metodo",
            field=models.CharField(default="POST", max_length=10),
        ),
        migrations.AlterField(
            model_name="estadisticausoeosda",
            name="parcela",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="estadisticas_eosda",
                to="informes.parcela",
            ),
        ),
        migrations.AlterField(
            model_name="estadisticausoeosda",
            name="requests_consumidos",
            field=models.IntegerField(default=1),
        ),
        migrations.AlterField(
            model_name="estadisticausoeosda",
            name="tiempo_respuesta",
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="estadisticausoeosda",
            name="tipo_operacion",
            field=models.CharField(
                choices=[
                    ("field_management", "Field Management"),
                    ("statistics", "Statistics"),
                    ("images", "Images"),
                    ("tiles", "Tiles"),
                ],
                max_length=50,
            ),
        ),
        migrations.AlterField(
            model_name="estadisticausoeosda",
            name="usuario",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="estadisticas_eosda",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
