# Generated by Django 5.2.8 on 2025-11-12 01:30

import datetime
import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("informes", "0008_configuracion_cache_eosda"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="indicemensual",
            name="fecha_imagen",
            field=models.DateField(
                blank=True,
                help_text="Fecha de captura de la imagen satelital",
                null=True,
                verbose_name="Fecha de la Imagen",
            ),
        ),
        migrations.AddField(
            model_name="indicemensual",
            name="imagen_ndmi",
            field=models.ImageField(
                blank=True,
                help_text="Imagen satelital del índice NDMI",
                null=True,
                upload_to="imagenes_satelitales/%Y/%m/ndmi/",
                verbose_name="Imagen NDMI",
            ),
        ),
        migrations.AddField(
            model_name="indicemensual",
            name="imagen_ndvi",
            field=models.ImageField(
                blank=True,
                help_text="Imagen satelital del índice NDVI",
                null=True,
                upload_to="imagenes_satelitales/%Y/%m/ndvi/",
                verbose_name="Imagen NDVI",
            ),
        ),
        migrations.AddField(
            model_name="indicemensual",
            name="imagen_savi",
            field=models.ImageField(
                blank=True,
                help_text="Imagen satelital del índice SAVI",
                null=True,
                upload_to="imagenes_satelitales/%Y/%m/savi/",
                verbose_name="Imagen SAVI",
            ),
        ),
        migrations.AddField(
            model_name="indicemensual",
            name="nubosidad_imagen",
            field=models.FloatField(
                blank=True,
                help_text="Porcentaje de nubosidad de la imagen satelital descargada",
                null=True,
                verbose_name="Nubosidad de la Imagen (%)",
            ),
        ),
        migrations.AddField(
            model_name="indicemensual",
            name="view_id_imagen",
            field=models.CharField(
                blank=True,
                help_text="ID de la vista satelital usada para las imágenes",
                max_length=50,
                null=True,
                verbose_name="View ID de la Imagen",
            ),
        ),
        migrations.AlterField(
            model_name="cachedatoseosda",
            name="cache_key",
            field=models.CharField(
                db_index=True,
                help_text="Hash único generado: field_id + fechas + indices",
                max_length=255,
                unique=True,
                verbose_name="Clave de Caché",
            ),
        ),
        migrations.AlterField(
            model_name="cachedatoseosda",
            name="calidad_promedio",
            field=models.FloatField(
                blank=True,
                help_text="Nubosidad promedio de las escenas (%)",
                null=True,
                verbose_name="Calidad Promedio",
            ),
        ),
        migrations.AlterField(
            model_name="cachedatoseosda",
            name="datos_json",
            field=models.JSONField(
                help_text="Respuesta completa de EOSDA en formato JSON",
                verbose_name="Datos en JSON",
            ),
        ),
        migrations.AlterField(
            model_name="cachedatoseosda",
            name="fecha_fin",
            field=models.DateField(db_index=True, verbose_name="Fecha Fin"),
        ),
        migrations.AlterField(
            model_name="cachedatoseosda",
            name="fecha_inicio",
            field=models.DateField(db_index=True, verbose_name="Fecha Inicio"),
        ),
        migrations.AlterField(
            model_name="cachedatoseosda",
            name="field_id",
            field=models.CharField(
                db_index=True, max_length=100, verbose_name="Field ID de EOSDA"
            ),
        ),
        migrations.AlterField(
            model_name="cachedatoseosda",
            name="indices",
            field=models.CharField(
                help_text="Formato: ndvi,ndmi,savi",
                max_length=100,
                verbose_name="Índices Solicitados",
            ),
        ),
        migrations.AlterField(
            model_name="cachedatoseosda",
            name="num_escenas",
            field=models.IntegerField(
                default=0,
                help_text="Cantidad de escenas satelitales retornadas",
                verbose_name="Número de Escenas",
            ),
        ),
        migrations.AlterField(
            model_name="cachedatoseosda",
            name="task_id",
            field=models.CharField(
                blank=True, max_length=100, null=True, verbose_name="Task ID de EOSDA"
            ),
        ),
        migrations.AlterField(
            model_name="cachedatoseosda",
            name="usado_en",
            field=models.DateTimeField(
                auto_now=True,
                help_text="Actualizado cada vez que se reutiliza el caché",
                verbose_name="Último Uso",
            ),
        ),
        migrations.AlterField(
            model_name="cachedatoseosda",
            name="valido_hasta",
            field=models.DateTimeField(
                help_text="Fecha de expiración del caché (7 días típicamente)",
                verbose_name="Válido Hasta",
            ),
        ),
        migrations.AlterField(
            model_name="cachedatoseosda",
            name="veces_usado",
            field=models.IntegerField(
                default=0,
                help_text="Contador de cuántas veces se ha reutilizado este caché",
                verbose_name="Veces Reutilizado",
            ),
        ),
        migrations.AlterField(
            model_name="configuracionreporte",
            name="costo_estimado",
            field=models.DecimalField(
                decimal_places=2,
                default=Decimal("0.00"),
                help_text="Cálculo automático según configuración",
                max_digits=10,
                verbose_name="Costo Estimado (USD)",
            ),
        ),
        migrations.AlterField(
            model_name="configuracionreporte",
            name="fecha_fin",
            field=models.DateField(
                default=datetime.date.today,
                help_text="Fin del período de análisis",
                verbose_name="Fecha de Fin",
            ),
        ),
        migrations.AlterField(
            model_name="configuracionreporte",
            name="fecha_generacion",
            field=models.DateTimeField(
                blank=True, null=True, verbose_name="Fecha de Generación"
            ),
        ),
        migrations.AlterField(
            model_name="configuracionreporte",
            name="fecha_inicio",
            field=models.DateField(
                help_text="Inicio del período de análisis",
                verbose_name="Fecha de Inicio",
            ),
        ),
        migrations.AlterField(
            model_name="configuracionreporte",
            name="frecuencia_imagenes",
            field=models.CharField(
                choices=[
                    ("mensual", "Mensual (1 imagen/mes)"),
                    ("bimensual", "Bimensual (1 imagen cada 2 meses)"),
                    ("trimestral", "Trimestral (1 imagen cada 3 meses)"),
                ],
                default="mensual",
                max_length=20,
                verbose_name="Frecuencia de Imágenes",
            ),
        ),
        migrations.AlterField(
            model_name="configuracionreporte",
            name="incluir_imagenes",
            field=models.BooleanField(
                default=False,
                help_text="Imágenes satelitales en el reporte PDF",
                verbose_name="Incluir Imágenes",
            ),
        ),
        migrations.AlterField(
            model_name="configuracionreporte",
            name="incluir_ndmi",
            field=models.BooleanField(
                default=False,
                help_text="Índice de Humedad (estrés hídrico)",
                verbose_name="Incluir NDMI",
            ),
        ),
        migrations.AlterField(
            model_name="configuracionreporte",
            name="incluir_ndvi",
            field=models.BooleanField(
                default=True,
                help_text="Índice de Vegetación (salud del cultivo)",
                verbose_name="Incluir NDVI",
            ),
        ),
        migrations.AlterField(
            model_name="configuracionreporte",
            name="incluir_savi",
            field=models.BooleanField(
                default=False,
                help_text="Índice Ajustado de Suelo (cobertura)",
                verbose_name="Incluir SAVI",
            ),
        ),
        migrations.AlterField(
            model_name="configuracionreporte",
            name="max_nubosidad",
            field=models.IntegerField(
                default=50,
                help_text="Porcentaje máximo de nubes (30% ideal, 50% aceptable)",
                validators=[
                    django.core.validators.MinValueValidator(0),
                    django.core.validators.MaxValueValidator(100),
                ],
                verbose_name="Máxima Nubosidad Permitida (%)",
            ),
        ),
        migrations.AlterField(
            model_name="configuracionreporte",
            name="reporte_generado",
            field=models.BooleanField(default=False, verbose_name="Reporte Generado"),
        ),
        migrations.AlterField(
            model_name="estadisticausoeosda",
            name="cache_key",
            field=models.CharField(
                blank=True, max_length=255, null=True, verbose_name="Clave de Caché"
            ),
        ),
        migrations.AlterField(
            model_name="estadisticausoeosda",
            name="codigo_respuesta",
            field=models.IntegerField(
                blank=True, null=True, verbose_name="Código HTTP"
            ),
        ),
        migrations.AlterField(
            model_name="estadisticausoeosda",
            name="desde_cache",
            field=models.BooleanField(
                default=False,
                help_text="Si los datos se obtuvieron de caché (0 requests)",
                verbose_name="Desde Caché",
            ),
        ),
        migrations.AlterField(
            model_name="estadisticausoeosda",
            name="endpoint",
            field=models.CharField(max_length=200, verbose_name="Endpoint"),
        ),
        migrations.AlterField(
            model_name="estadisticausoeosda",
            name="exitoso",
            field=models.BooleanField(default=True, verbose_name="Exitoso"),
        ),
        migrations.AlterField(
            model_name="estadisticausoeosda",
            name="mensaje_error",
            field=models.TextField(
                blank=True, null=True, verbose_name="Mensaje de Error"
            ),
        ),
        migrations.AlterField(
            model_name="estadisticausoeosda",
            name="metodo",
            field=models.CharField(
                default="POST", max_length=10, verbose_name="Método HTTP"
            ),
        ),
        migrations.AlterField(
            model_name="estadisticausoeosda",
            name="parcela",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="estadisticas_eosda",
                to="informes.parcela",
                verbose_name="Parcela",
            ),
        ),
        migrations.AlterField(
            model_name="estadisticausoeosda",
            name="requests_consumidos",
            field=models.IntegerField(
                default=1,
                help_text="Número de requests de API consumidos",
                verbose_name="Requests Consumidos",
            ),
        ),
        migrations.AlterField(
            model_name="estadisticausoeosda",
            name="tiempo_respuesta",
            field=models.FloatField(
                blank=True, null=True, verbose_name="Tiempo de Respuesta (segundos)"
            ),
        ),
        migrations.AlterField(
            model_name="estadisticausoeosda",
            name="tipo_operacion",
            field=models.CharField(
                choices=[
                    ("field_management", "Field Management (Crear Campo)"),
                    ("statistics", "Statistics (Obtener Datos)"),
                    ("images", "Images (Imágenes Satelitales)"),
                    ("tiles", "Tiles (Mosaicos)"),
                ],
                max_length=50,
                verbose_name="Tipo de Operación",
            ),
        ),
        migrations.AlterField(
            model_name="estadisticausoeosda",
            name="usuario",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="estadisticas_eosda",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Usuario",
            ),
        ),
        migrations.AddIndex(
            model_name="cachedatoseosda",
            index=models.Index(
                fields=["field_id", "fecha_inicio", "fecha_fin"],
                name="informes_ca_field_i_7a5936_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="cachedatoseosda",
            index=models.Index(
                fields=["cache_key"], name="informes_ca_cache_k_0bd0ff_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="cachedatoseosda",
            index=models.Index(
                fields=["valido_hasta"], name="informes_ca_valido__94ed5a_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="configuracionreporte",
            index=models.Index(
                fields=["parcela", "-creado_en"], name="informes_co_parcela_aba29e_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="configuracionreporte",
            index=models.Index(
                fields=["usuario", "-creado_en"], name="informes_co_usuario_9931c6_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="estadisticausoeosda",
            index=models.Index(
                fields=["usuario", "-creado_en"], name="informes_es_usuario_af1514_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="estadisticausoeosda",
            index=models.Index(
                fields=["parcela", "-creado_en"], name="informes_es_parcela_e9c5d5_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="estadisticausoeosda",
            index=models.Index(
                fields=["tipo_operacion", "-creado_en"],
                name="informes_es_tipo_op_f68540_idx",
            ),
        ),
    ]
