# Generated by Django 5.1.2 on 2025-11-21 21:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("informes", "0011_agregar_cache_gemini"),
    ]

    operations = [
        migrations.AddField(
            model_name="indicemensual",
            name="coordenadas_imagen",
            field=models.JSONField(
                blank=True,
                help_text="Bounding box y centroide de la imagen satelital [min_lat, min_lon, max_lat, max_lon]",
                null=True,
                verbose_name="Coordenadas de la Imagen",
            ),
        ),
        migrations.AddField(
            model_name="indicemensual",
            name="metadatos_imagen",
            field=models.JSONField(
                blank=True,
                help_text="Metadatos completos de EOSDA: coordenadas, bbox, satélite, resolución, etc.",
                null=True,
                verbose_name="Metadatos Espaciales de Imagen",
            ),
        ),
        migrations.AddField(
            model_name="indicemensual",
            name="resolucion_imagen",
            field=models.FloatField(
                blank=True,
                help_text="Resolución espacial de la imagen en metros por píxel",
                null=True,
                verbose_name="Resolución Espacial (m)",
            ),
        ),
        migrations.AddField(
            model_name="indicemensual",
            name="satelite_imagen",
            field=models.CharField(
                blank=True,
                help_text="Satélite que capturó la imagen (ej: Sentinel-2, Landsat-8)",
                max_length=50,
                null=True,
                verbose_name="Satélite Fuente",
            ),
        ),
    ]
