# Generated by Django 5.1.2 on 2025-12-29 21:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("informes", "0014_add_configuracion_personalizada"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="clienteinvitacion",
            name="bloqueada",
        ),
        migrations.RemoveField(
            model_name="clienteinvitacion",
            name="intentos_uso",
        ),
        migrations.RemoveField(
            model_name="clienteinvitacion",
            name="ip_ultimo_intento",
        ),
        migrations.RemoveField(
            model_name="clienteinvitacion",
            name="max_intentos",
        ),
        migrations.RemoveField(
            model_name="informe",
            name="configuracion",
        ),
        migrations.DeleteModel(
            name="PlantillaInforme",
        ),
    ]
