# Generated by Django 5.1.2 on 2026-01-08 15:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("informes", "0015_remove_clienteinvitacion_bloqueada_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="parcela",
            name="ultima_calidad_datos",
            field=models.CharField(
                blank=True,
                choices=[
                    ("excelente", "Excelente (< 20% nubosidad)"),
                    ("buena", "Buena (< 50% nubosidad)"),
                    ("aceptable", "Aceptable (< 80% nubosidad)"),
                ],
                help_text="Calidad de las últimas imágenes satelitales descargadas",
                max_length=20,
                null=True,
                verbose_name="Última Calidad de Datos",
            ),
        ),
        migrations.AddField(
            model_name="parcela",
            name="ultimo_umbral_nubosidad",
            field=models.IntegerField(
                blank=True,
                help_text="Umbral de nubosidad máximo usado en la última descarga (%)",
                null=True,
                verbose_name="Último Umbral de Nubosidad Usado",
            ),
        ),
    ]
