# Generated by Django 5.1.2 on 2026-01-09 22:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("informes", "0016_parcela_ultima_calidad_datos_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="informe",
            name="estado_pago",
            field=models.CharField(
                default="pendiente",
                help_text="Estado del pago del informe (pendiente, pagado, etc.)",
                max_length=20,
                verbose_name="Estado de Pago",
            ),
        ),
    ]
