# Generated by Django 5.1.2 on 2026-01-09 22:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("informes", "0017_informe_estado_pago"),
    ]

    operations = [
        migrations.AddField(
            model_name="informe",
            name="metodo_pago",
            field=models.CharField(
                default="sin_definir",
                help_text="Método utilizado para el pago del informe (transferencia, tarjeta, etc.)",
                max_length=50,
                verbose_name="Método de Pago",
            ),
        ),
    ]
