# Generated by Django 5.1.2 on 2026-01-09 22:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("informes", "0018_informe_metodo_pago"),
    ]

    operations = [
        migrations.AlterField(
            model_name="informe",
            name="referencia_pago",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
